// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAgentMCPServer = `-- name: AddAgentMCPServer :exec
INSERT INTO agent_mcp_servers (agent_id, mcp_server_id, team_id, allow)
VALUES ($1, $2, $3, $4)
`

type AddAgentMCPServerParams struct {
	AgentID     uuid.UUID
	McpServerID uuid.UUID
	TeamID      uuid.UUID
	Allow       []string
}

func (q *Queries) AddAgentMCPServer(ctx context.Context, arg AddAgentMCPServerParams) error {
	_, err := q.db.Exec(ctx, addAgentMCPServer,
		arg.AgentID,
		arg.McpServerID,
		arg.TeamID,
		arg.Allow,
	)
	return err
}

const addAgentSkills = `-- name: AddAgentSkills :exec
INSERT INTO agent_skills (agent_id, skill_id, team_id)
SELECT $1, unnest($2::uuid[]), $3
`

type AddAgentSkillsParams struct {
	AgentID  uuid.UUID
	SkillIds []uuid.UUID
	TeamID   uuid.UUID
}

// One statement for every skill: each grant is only ids, so there is nothing
// per row that needs its own INSERT, and one statement is one outbox row.
func (q *Queries) AddAgentSkills(ctx context.Context, arg AddAgentSkillsParams) error {
	_, err := q.db.Exec(ctx, addAgentSkills, arg.AgentID, arg.SkillIds, arg.TeamID)
	return err
}

const clearAgentMCPServers = `-- name: ClearAgentMCPServers :exec
DELETE FROM agent_mcp_servers WHERE agent_id = $1
`

func (q *Queries) ClearAgentMCPServers(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAgentMCPServers, agentID)
	return err
}

const clearAgentSkills = `-- name: ClearAgentSkills :exec
DELETE FROM agent_skills WHERE agent_id = $1
`

func (q *Queries) ClearAgentSkills(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAgentSkills, agentID)
	return err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    team_id, name, description, kind, instructions,
    model_name, max_tokens, temperature, pattern, max_steps, steer_continuations,
    output_schema, parser, parser_model_name, parser_max_tokens, parser_temperature
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16
) RETURNING id, team_id, name, description, kind, instructions, model_name, max_tokens, temperature, pattern, max_steps, steer_continuations, output_schema, parser, parser_model_name, parser_max_tokens, parser_temperature, created_at, updated_at
`

type CreateAgentParams struct {
	TeamID             uuid.UUID
	Name               string
	Description        string
	Kind               string
	Instructions       string
	ModelName          string
	MaxTokens          int32
	Temperature        *float64
	Pattern            string
	MaxSteps           int32
	SteerContinuations int32
	OutputSchema       []byte
	Parser             bool
	ParserModelName    *string
	ParserMaxTokens    *int32
	ParserTemperature  *float64
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.Instructions,
		arg.ModelName,
		arg.MaxTokens,
		arg.Temperature,
		arg.Pattern,
		arg.MaxSteps,
		arg.SteerContinuations,
		arg.OutputSchema,
		arg.Parser,
		arg.ParserModelName,
		arg.ParserMaxTokens,
		arg.ParserTemperature,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Instructions,
		&i.ModelName,
		&i.MaxTokens,
		&i.Temperature,
		&i.Pattern,
		&i.MaxSteps,
		&i.SteerContinuations,
		&i.OutputSchema,
		&i.Parser,
		&i.ParserModelName,
		&i.ParserMaxTokens,
		&i.ParserTemperature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, team_id, name, description, kind, instructions, model_name, max_tokens, temperature, pattern, max_steps, steer_continuations, output_schema, parser, parser_model_name, parser_max_tokens, parser_temperature, created_at, updated_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Instructions,
		&i.ModelName,
		&i.MaxTokens,
		&i.Temperature,
		&i.Pattern,
		&i.MaxSteps,
		&i.SteerContinuations,
		&i.OutputSchema,
		&i.Parser,
		&i.ParserModelName,
		&i.ParserMaxTokens,
		&i.ParserTemperature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentMCPServers = `-- name: ListAgentMCPServers :many
SELECT agent_id, mcp_server_id, team_id, allow FROM agent_mcp_servers WHERE agent_id = $1 ORDER BY mcp_server_id
`

func (q *Queries) ListAgentMCPServers(ctx context.Context, agentID uuid.UUID) ([]AgentMcpServer, error) {
	rows, err := q.db.Query(ctx, listAgentMCPServers, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentMcpServer
	for rows.Next() {
		var i AgentMcpServer
		if err := rows.Scan(
			&i.AgentID,
			&i.McpServerID,
			&i.TeamID,
			&i.Allow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSkills = `-- name: ListAgentSkills :many
SELECT skill_id FROM agent_skills WHERE agent_id = $1 ORDER BY skill_id
`

func (q *Queries) ListAgentSkills(ctx context.Context, agentID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAgentSkills, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var skill_id uuid.UUID
		if err := rows.Scan(&skill_id); err != nil {
			return nil, err
		}
		items = append(items, skill_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByTeam = `-- name: ListAgentsByTeam :many
SELECT id, team_id, name, description, kind, instructions, model_name, max_tokens, temperature, pattern, max_steps, steer_continuations, output_schema, parser, parser_model_name, parser_max_tokens, parser_temperature, created_at, updated_at FROM agents
WHERE team_id = $1
  AND (NOT $2::bool
   OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListAgentsByTeamParams struct {
	TeamID         uuid.UUID
	UseCursor      bool
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageSize       int32
}

func (q *Queries) ListAgentsByTeam(ctx context.Context, arg ListAgentsByTeamParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByTeam,
		arg.TeamID,
		arg.UseCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.Instructions,
			&i.ModelName,
			&i.MaxTokens,
			&i.Temperature,
			&i.Pattern,
			&i.MaxSteps,
			&i.SteerContinuations,
			&i.OutputSchema,
			&i.Parser,
			&i.ParserModelName,
			&i.ParserMaxTokens,
			&i.ParserTemperature,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET
    name                = $1,
    description         = $2,
    instructions        = $3,
    model_name          = $4,
    max_tokens          = $5,
    temperature         = $6,
    pattern             = $7,
    max_steps           = $8,
    steer_continuations = $9,
    output_schema       = $10,
    parser              = $11,
    parser_model_name   = $12,
    parser_max_tokens   = $13,
    parser_temperature  = $14,
    updated_at          = now()
WHERE id = $15
RETURNING id, team_id, name, description, kind, instructions, model_name, max_tokens, temperature, pattern, max_steps, steer_continuations, output_schema, parser, parser_model_name, parser_max_tokens, parser_temperature, created_at, updated_at
`

type UpdateAgentParams struct {
	Name               string
	Description        string
	Instructions       string
	ModelName          string
	MaxTokens          int32
	Temperature        *float64
	Pattern            string
	MaxSteps           int32
	SteerContinuations int32
	OutputSchema       []byte
	Parser             bool
	ParserModelName    *string
	ParserMaxTokens    *int32
	ParserTemperature  *float64
	ID                 uuid.UUID
}

// kind and team_id are absent on purpose: a replace can change neither.
func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.ModelName,
		arg.MaxTokens,
		arg.Temperature,
		arg.Pattern,
		arg.MaxSteps,
		arg.SteerContinuations,
		arg.OutputSchema,
		arg.Parser,
		arg.ParserModelName,
		arg.ParserMaxTokens,
		arg.ParserTemperature,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Instructions,
		&i.ModelName,
		&i.MaxTokens,
		&i.Temperature,
		&i.Pattern,
		&i.MaxSteps,
		&i.SteerContinuations,
		&i.OutputSchema,
		&i.Parser,
		&i.ParserModelName,
		&i.ParserMaxTokens,
		&i.ParserTemperature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
