// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countAttachmentsByObjectKey = `-- name: CountAttachmentsByObjectKey :one
SELECT count(*) FROM attachments WHERE object_key = $1
`

// Deletion asks this before removing an object: another row pointing at the
// same key means the bytes are still somebody's. Always 1 today, and not
// always 1 once identical files share an object.
func (q *Queries) CountAttachmentsByObjectKey(ctx context.Context, objectKey string) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachmentsByObjectKey, objectKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (message_id, object_key, key_version, media_type, size_bytes, filename)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, message_id, object_key, key_version, media_type, size_bytes, filename, created_at
`

type CreateAttachmentParams struct {
	MessageID  uuid.UUID
	ObjectKey  string
	KeyVersion int32
	MediaType  string
	SizeBytes  int64
	Filename   string
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.MessageID,
		arg.ObjectKey,
		arg.KeyVersion,
		arg.MediaType,
		arg.SizeBytes,
		arg.Filename,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ObjectKey,
		&i.KeyVersion,
		&i.MediaType,
		&i.SizeBytes,
		&i.Filename,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentWithTeam = `-- name: GetAttachmentWithTeam :one
SELECT a.id, a.message_id, a.object_key, a.key_version, a.media_type, a.size_bytes, a.filename, a.created_at, s.team_id
FROM attachments a
JOIN messages m ON m.id = a.message_id
JOIN sessions s ON s.id = m.session_id
WHERE a.id = $1
`

type GetAttachmentWithTeamRow struct {
	Attachment Attachment
	TeamID     uuid.UUID
}

// The read path's only query. It returns the team in the same round trip that
// fetches the row, so authorisation never needs a second one — and the team is
// what selects the key that opens the object.
//
// Through sessions, not through channels. A session carries its own team and
// always has one; its channel_id is nullable, because the dashboard and the
// API start sessions with no channel behind them. Joining through channels
// would return no row for those, and an attachment that exists would read as
// one that does not.
func (q *Queries) GetAttachmentWithTeam(ctx context.Context, id uuid.UUID) (GetAttachmentWithTeamRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentWithTeam, id)
	var i GetAttachmentWithTeamRow
	err := row.Scan(
		&i.Attachment.ID,
		&i.Attachment.MessageID,
		&i.Attachment.ObjectKey,
		&i.Attachment.KeyVersion,
		&i.Attachment.MediaType,
		&i.Attachment.SizeBytes,
		&i.Attachment.Filename,
		&i.Attachment.CreatedAt,
		&i.TeamID,
	)
	return i, err
}

const listAttachmentsByMessage = `-- name: ListAttachmentsByMessage :many
SELECT id, message_id, object_key, key_version, media_type, size_bytes, filename, created_at FROM attachments
WHERE message_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListAttachmentsByMessage(ctx context.Context, messageID uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ObjectKey,
			&i.KeyVersion,
			&i.MediaType,
			&i.SizeBytes,
			&i.Filename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
