// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAttachmentsByObjectKey = `-- name: CountAttachmentsByObjectKey :one
SELECT count(*) FROM attachments WHERE object_key = $1
`

// The sweeper asks this before removing an object: another row pointing at the
// same key means the bytes are still somebody's, and the tombstone is dropped
// rather than acted on. Always 1 today, and not always 1 once identical files
// share one.
func (q *Queries) CountAttachmentsByObjectKey(ctx context.Context, objectKey string) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachmentsByObjectKey, objectKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (
    message_id, session_id, team_id,
    object_key, key_version, media_type, size_bytes, filename
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, message_id, object_key, key_version, media_type, size_bytes, filename, created_at, session_id, team_id
`

type CreateAttachmentParams struct {
	MessageID  uuid.UUID
	SessionID  uuid.UUID
	TeamID     uuid.UUID
	ObjectKey  string
	KeyVersion int32
	MediaType  string
	SizeBytes  int64
	Filename   string
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.MessageID,
		arg.SessionID,
		arg.TeamID,
		arg.ObjectKey,
		arg.KeyVersion,
		arg.MediaType,
		arg.SizeBytes,
		arg.Filename,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ObjectKey,
		&i.KeyVersion,
		&i.MediaType,
		&i.SizeBytes,
		&i.Filename,
		&i.CreatedAt,
		&i.SessionID,
		&i.TeamID,
	)
	return i, err
}

const getAttachmentInSession = `-- name: GetAttachmentInSession :one
SELECT id, message_id, object_key, key_version, media_type, size_bytes, filename, created_at, session_id, team_id FROM attachments
WHERE id = $1 AND session_id = $2
`

type GetAttachmentInSessionParams struct {
	ID        uuid.UUID
	SessionID uuid.UUID
}

// The bytes route's scope check, done in SQL rather than in Go. The handler
// has already resolved the session and proven the caller may read it; naming
// the session here means an attachment from another conversation is a missing
// row rather than a comparison somebody has to remember to write.
func (q *Queries) GetAttachmentInSession(ctx context.Context, arg GetAttachmentInSessionParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentInSession, arg.ID, arg.SessionID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ObjectKey,
		&i.KeyVersion,
		&i.MediaType,
		&i.SizeBytes,
		&i.Filename,
		&i.CreatedAt,
		&i.SessionID,
		&i.TeamID,
	)
	return i, err
}

const listAttachmentsByMessage = `-- name: ListAttachmentsByMessage :many
SELECT id, message_id, object_key, key_version, media_type, size_bytes, filename, created_at, session_id, team_id FROM attachments
WHERE message_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListAttachmentsByMessage(ctx context.Context, messageID uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ObjectKey,
			&i.KeyVersion,
			&i.MediaType,
			&i.SizeBytes,
			&i.Filename,
			&i.CreatedAt,
			&i.SessionID,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsBySession = `-- name: ListAttachmentsBySession :many
SELECT id, message_id, object_key, key_version, media_type, size_bytes, filename, created_at, session_id, team_id FROM attachments
WHERE session_id = $1
  AND (NOT $2::bool
   OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListAttachmentsBySessionParams struct {
	SessionID      uuid.UUID
	UseCursor      bool
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageSize       int32
}

// Everything a session has accumulated, which is what an agent reads to
// answer "the file I sent earlier" — a message can name one that arrived
// twenty messages ago. Straight off attachments.session_id rather than
// through messages: no index can express that join, so it reads every message
// in the session and every attachment in the database to return a few.
//
// Ordered newest first and paged on (created_at, id), matching messages and
// sessions: a page boundary has to be a total order, and created_at repeats
// when several files arrive on one delivery.
func (q *Queries) ListAttachmentsBySession(ctx context.Context, arg ListAttachmentsBySessionParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsBySession,
		arg.SessionID,
		arg.UseCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ObjectKey,
			&i.KeyVersion,
			&i.MediaType,
			&i.SizeBytes,
			&i.Filename,
			&i.CreatedAt,
			&i.SessionID,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
