// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (team_id, provider, name) VALUES ($1, $2, $3) RETURNING id, team_id, provider, name, created_at, updated_at
`

type CreateChannelParams struct {
	TeamID   uuid.UUID
	Provider string
	Name     string
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.TeamID, arg.Provider, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, team_id, provider, name, created_at, updated_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelsByTeam = `-- name: ListChannelsByTeam :many
SELECT id, team_id, provider, name, created_at, updated_at FROM channels
WHERE team_id = $1
  AND (NOT $2::bool
   OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListChannelsByTeamParams struct {
	TeamID         uuid.UUID
	UseCursor      bool
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageSize       int32
}

func (q *Queries) ListChannelsByTeam(ctx context.Context, arg ListChannelsByTeamParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsByTeam,
		arg.TeamID,
		arg.UseCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Provider,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
