// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertSkillFiles implements pgx.CopyFromSource.
type iteratorForInsertSkillFiles struct {
	rows                 []InsertSkillFilesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertSkillFiles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertSkillFiles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SkillID,
		r.rows[0].TeamID,
		r.rows[0].Path,
		r.rows[0].Size,
		r.rows[0].Sha256,
		r.rows[0].MediaType,
		r.rows[0].ObjectKey,
	}, nil
}

func (r iteratorForInsertSkillFiles) Err() error {
	return nil
}

// One COPY for every file of a skill: up to two hundred rows is one round
// trip, not two hundred, and all of them land inside the caller's transaction.
func (q *Queries) InsertSkillFiles(ctx context.Context, arg []InsertSkillFilesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"skill_files"}, []string{"skill_id", "team_id", "path", "size", "sha256", "media_type", "object_key"}, &iteratorForInsertSkillFiles{rows: arg})
}
