// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: graph_outbox.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimGraphOutbox = `-- name: ClaimGraphOutbox :many
UPDATE graph_outbox
SET attempts = attempts + 1, last_attempt_at = now()
WHERE id IN (
    SELECT o.id FROM graph_outbox o
    WHERE o.last_attempt_at IS NULL OR o.last_attempt_at < $1
    ORDER BY o.last_attempt_at NULLS FIRST, o.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, team_id, entity, entity_id, created_at, attempts, last_attempt_at
`

type ClaimGraphOutboxParams struct {
	RetryBefore *time.Time
	BatchSize   int32
}

// A claim is a committed mark, not a held lock: the projector embeds and
// writes FalkorDB between claiming and forgetting, and a transaction held open
// across a network call is a connection and a lock nobody else can have.
// SKIP LOCKED only keeps two workers from marking the same row at once.
func (q *Queries) ClaimGraphOutbox(ctx context.Context, arg ClaimGraphOutboxParams) ([]GraphOutbox, error) {
	rows, err := q.db.Query(ctx, claimGraphOutbox, arg.RetryBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphOutbox
	for rows.Next() {
		var i GraphOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Entity,
			&i.EntityID,
			&i.CreatedAt,
			&i.Attempts,
			&i.LastAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forgetGraphOutbox = `-- name: ForgetGraphOutbox :exec
DELETE FROM graph_outbox WHERE id = ANY($1::bigint[])
`

// Only the ids that were claimed and projected. A row written for the same
// entity after the claim has an id of its own and stays, so a change made
// while the projector was reading is projected again rather than lost.
func (q *Queries) ForgetGraphOutbox(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, forgetGraphOutbox, ids)
	return err
}

const graphOutboxBacklog = `-- name: GraphOutboxBacklog :many
SELECT count(*) OVER () AS outstanding, created_at AS oldest
FROM graph_outbox
ORDER BY created_at
LIMIT 1
`

type GraphOutboxBacklogRow struct {
	Outstanding int64
	Oldest      time.Time
}

// The same shape as the tombstones' backlog, for the same reason: one row
// when anything is outstanding, none when nothing is.
func (q *Queries) GraphOutboxBacklog(ctx context.Context) ([]GraphOutboxBacklogRow, error) {
	rows, err := q.db.Query(ctx, graphOutboxBacklog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphOutboxBacklogRow
	for rows.Next() {
		var i GraphOutboxBacklogRow
		if err := rows.Scan(&i.Outstanding, &i.Oldest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamIDs = `-- name: ListTeamIDs :many
SELECT id FROM teams ORDER BY id
`

func (q *Queries) ListTeamIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTeamIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
