// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_servers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMCPServer = `-- name: CreateMCPServer :one
INSERT INTO mcp_servers (team_id, name, url, command, env, auth_secret_ref, bare)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, team_id, name, url, command, env, auth_secret_ref, bare, discovered_at, created_at, updated_at
`

type CreateMCPServerParams struct {
	TeamID        uuid.UUID
	Name          string
	Url           *string
	Command       []string
	Env           []byte
	AuthSecretRef *string
	Bare          bool
}

func (q *Queries) CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, createMCPServer,
		arg.TeamID,
		arg.Name,
		arg.Url,
		arg.Command,
		arg.Env,
		arg.AuthSecretRef,
		arg.Bare,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Url,
		&i.Command,
		&i.Env,
		&i.AuthSecretRef,
		&i.Bare,
		&i.DiscoveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMCPServer = `-- name: DeleteMCPServer :exec
DELETE FROM mcp_servers WHERE id = $1
`

func (q *Queries) DeleteMCPServer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMCPServer, id)
	return err
}

const getMCPServer = `-- name: GetMCPServer :one
SELECT id, team_id, name, url, command, env, auth_secret_ref, bare, discovered_at, created_at, updated_at FROM mcp_servers WHERE id = $1
`

func (q *Queries) GetMCPServer(ctx context.Context, id uuid.UUID) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServer, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Url,
		&i.Command,
		&i.Env,
		&i.AuthSecretRef,
		&i.Bare,
		&i.DiscoveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMCPServersByTeam = `-- name: ListMCPServersByTeam :many
SELECT id, team_id, name, url, command, env, auth_secret_ref, bare, discovered_at, created_at, updated_at FROM mcp_servers
WHERE team_id = $1
  AND (NOT $2::bool
   OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListMCPServersByTeamParams struct {
	TeamID         uuid.UUID
	UseCursor      bool
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageSize       int32
}

func (q *Queries) ListMCPServersByTeam(ctx context.Context, arg ListMCPServersByTeamParams) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listMCPServersByTeam,
		arg.TeamID,
		arg.UseCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpServer
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Url,
			&i.Command,
			&i.Env,
			&i.AuthSecretRef,
			&i.Bare,
			&i.DiscoveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMCPServerDiscovered = `-- name: MarkMCPServerDiscovered :exec
UPDATE mcp_servers SET discovered_at = now() WHERE id = $1
`

func (q *Queries) MarkMCPServerDiscovered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMCPServerDiscovered, id)
	return err
}

const updateMCPServer = `-- name: UpdateMCPServer :one
UPDATE mcp_servers SET
    name            = $1,
    url             = $2,
    command         = $3,
    env             = $4,
    auth_secret_ref = $5,
    bare            = $6,
    discovered_at   = CASE
        WHEN url IS NOT DISTINCT FROM $2
         AND command IS NOT DISTINCT FROM $3::text[]
        THEN discovered_at
    END,
    updated_at      = now()
WHERE id = $7
RETURNING id, team_id, name, url, command, env, auth_secret_ref, bare, discovered_at, created_at, updated_at
`

type UpdateMCPServerParams struct {
	Name          string
	Url           *string
	Command       []string
	Env           []byte
	AuthSecretRef *string
	Bare          bool
	ID            uuid.UUID
}

// A server pointed somewhere else has not been discovered there, so a changed
// transport clears discovered_at. The tools stay until the next discovery
// replaces them: an agent granted this server keeps what it had rather than
// losing every tool to an edit.
func (q *Queries) UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, updateMCPServer,
		arg.Name,
		arg.Url,
		arg.Command,
		arg.Env,
		arg.AuthSecretRef,
		arg.Bare,
		arg.ID,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Url,
		&i.Command,
		&i.Env,
		&i.AuthSecretRef,
		&i.Bare,
		&i.DiscoveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
