// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_tools.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteMCPToolsNotIn = `-- name: DeleteMCPToolsNotIn :exec
DELETE FROM mcp_tools
WHERE mcp_server_id = $1
  AND name <> ALL($2::text[])
`

type DeleteMCPToolsNotInParams struct {
	McpServerID uuid.UUID
	Names       []string
}

// An empty list deletes every tool of the server: `<> ALL('{}')` is true for
// every row, which is right for a server that now lists nothing.
func (q *Queries) DeleteMCPToolsNotIn(ctx context.Context, arg DeleteMCPToolsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteMCPToolsNotIn, arg.McpServerID, arg.Names)
	return err
}

const getMCPTool = `-- name: GetMCPTool :one
SELECT id, mcp_server_id, team_id, name, description, input_schema, created_at, updated_at FROM mcp_tools WHERE id = $1
`

func (q *Queries) GetMCPTool(ctx context.Context, id uuid.UUID) (McpTool, error) {
	row := q.db.QueryRow(ctx, getMCPTool, id)
	var i McpTool
	err := row.Scan(
		&i.ID,
		&i.McpServerID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.InputSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMCPToolsByServer = `-- name: ListMCPToolsByServer :many
SELECT id, mcp_server_id, team_id, name, description, input_schema, created_at, updated_at FROM mcp_tools WHERE mcp_server_id = $1 ORDER BY name
`

func (q *Queries) ListMCPToolsByServer(ctx context.Context, mcpServerID uuid.UUID) ([]McpTool, error) {
	rows, err := q.db.Query(ctx, listMCPToolsByServer, mcpServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpTool
	for rows.Next() {
		var i McpTool
		if err := rows.Scan(
			&i.ID,
			&i.McpServerID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.InputSchema,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMCPTool = `-- name: UpsertMCPTool :exec
INSERT INTO mcp_tools (mcp_server_id, team_id, name, description, input_schema)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (mcp_server_id, name) DO UPDATE SET
    description  = EXCLUDED.description,
    input_schema = EXCLUDED.input_schema,
    updated_at   = now()
WHERE (mcp_tools.description, mcp_tools.input_schema)
      IS DISTINCT FROM (EXCLUDED.description, EXCLUDED.input_schema)
`

type UpsertMCPToolParams struct {
	McpServerID uuid.UUID
	TeamID      uuid.UUID
	Name        string
	Description string
	InputSchema []byte
}

// A tool whose description and schema are unchanged is not rewritten, so a
// discovery that finds nothing new leaves nothing in the outbox and costs the
// projector nothing.
func (q *Queries) UpsertMCPTool(ctx context.Context, arg UpsertMCPToolParams) error {
	_, err := q.db.Exec(ctx, upsertMCPTool,
		arg.McpServerID,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.InputSchema,
	)
	return err
}
