// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMessagesByChannel = `-- name: CountMessagesByChannel :one
SELECT count(*) FROM messages WHERE channel_id = $1
`

func (q *Queries) CountMessagesByChannel(ctx context.Context, channelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesByChannel, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertMessage = `-- name: InsertMessage :execrows
INSERT INTO messages (channel_id, user_id, external_id, conversation_ref, text, sent_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (channel_id, external_id) DO NOTHING
`

type InsertMessageParams struct {
	ChannelID       uuid.UUID
	UserID          uuid.UUID
	ExternalID      string
	ConversationRef string
	Text            string
	SentAt          *time.Time
}

// InsertMessage reports the rows written, so a caller can tell a new message
// from a replay without asking first. Both answers are a 200; the difference
// is only whether anything downstream should run.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMessage,
		arg.ChannelID,
		arg.UserID,
		arg.ExternalID,
		arg.ConversationRef,
		arg.Text,
		arg.SentAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMessagesByChannel = `-- name: ListMessagesByChannel :many
SELECT id, channel_id, user_id, external_id, conversation_ref, text, sent_at, received_at FROM messages
WHERE channel_id = $1
  AND (NOT $2::bool
   OR (received_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY received_at DESC, id DESC
LIMIT $5
`

type ListMessagesByChannelParams struct {
	ChannelID       uuid.UUID
	UseCursor       bool
	AfterReceivedAt time.Time
	AfterID         uuid.UUID
	PageSize        int32
}

func (q *Queries) ListMessagesByChannel(ctx context.Context, arg ListMessagesByChannelParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByChannel,
		arg.ChannelID,
		arg.UseCursor,
		arg.AfterReceivedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.ExternalID,
			&i.ConversationRef,
			&i.Text,
			&i.SentAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
