// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMessagesBySession = `-- name: CountMessagesBySession :one
SELECT count(*) FROM messages WHERE session_id = $1
`

func (q *Queries) CountMessagesBySession(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (channel_id, session_id, user_id, external_id, text, sent_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (channel_id, external_id) DO NOTHING
RETURNING id
`

type InsertMessageParams struct {
	ChannelID  uuid.UUID
	SessionID  uuid.UUID
	UserID     uuid.UUID
	ExternalID string
	Text       string
	SentAt     *time.Time
}

// InsertMessage returns the id it wrote, and no row at all for a replay. Both
// answers are a 200; the difference is whether anything downstream should run.
// pgx reports the second as ErrNoRows, which carries the same information the
// row count used to and also names the message, which attachments need.
//
// DO NOTHING rather than a DO UPDATE that always returns. A no-op
// `SET external_id = EXCLUDED.external_id` writes a new row version anyway:
// measured on 18.6, 200 replays of a single row took the heap from 8 kB to
// 16 kB. Replays are the hot case here, not the rare one — a provider that
// does not get its 200 retries — and on a replay there is nothing to attach,
// because the files were stored the first time.
//
// The uniqueness is still per channel rather than per session: a provider's
// message id is unique within its channel, and a retry that arrived after a
// session closed would otherwise be stored twice under two sessions.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ChannelID,
		arg.SessionID,
		arg.UserID,
		arg.ExternalID,
		arg.Text,
		arg.SentAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, channel_id, user_id, external_id, text, sent_at, received_at, session_id FROM messages
WHERE session_id = $1
  AND (NOT $2::bool
   OR (received_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY received_at DESC, id DESC
LIMIT $5
`

type ListMessagesBySessionParams struct {
	SessionID       uuid.UUID
	UseCursor       bool
	AfterReceivedAt time.Time
	AfterID         uuid.UUID
	PageSize        int32
}

func (q *Queries) ListMessagesBySession(ctx context.Context, arg ListMessagesBySessionParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBySession,
		arg.SessionID,
		arg.UseCursor,
		arg.AfterReceivedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.ExternalID,
			&i.Text,
			&i.SentAt,
			&i.ReceivedAt,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
