// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Attachment struct {
	ID         uuid.UUID
	MessageID  uuid.UUID
	ObjectKey  string
	KeyVersion int32
	MediaType  string
	SizeBytes  int64
	Filename   string
	CreatedAt  time.Time
}

type Channel struct {
	ID        uuid.UUID
	TeamID    uuid.UUID
	Provider  string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ChannelSender struct {
	ChannelID uuid.UUID
	SenderRef string
	UserID    uuid.UUID
	CreatedAt time.Time
}

type Message struct {
	ID         uuid.UUID
	ChannelID  uuid.UUID
	UserID     uuid.UUID
	ExternalID string
	Text       string
	SentAt     *time.Time
	ReceivedAt time.Time
	SessionID  uuid.UUID
}

type PendingSender struct {
	ChannelID  uuid.UUID
	SenderRef  string
	SenderName string
	FirstSeen  time.Time
	LastSeen   time.Time
	SeenCount  int32
}

type Permission struct {
	Name        string
	Description string
}

type Role struct {
	Name        string
	Description string
}

type RolePermission struct {
	Role   string
	Action string
}

type RoutePermission struct {
	Method     string
	Path       string
	Permission *string
	Scope      string
}

type Session struct {
	ID            uuid.UUID
	TeamID        uuid.UUID
	ChannelID     *uuid.UUID
	ProviderRef   *string
	Kind          string
	Status        string
	StartedAt     time.Time
	LastMessageAt time.Time
	UserID        *uuid.UUID
}

type Team struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeamMember struct {
	TeamID    uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Issuer    string
	Subject   string
	Email     *string
	CreatedAt time.Time
	UpdatedAt time.Time
}
