// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Channel struct {
	ID        uuid.UUID
	TeamID    uuid.UUID
	Provider  string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Permission struct {
	Name        string
	Description string
}

type Role struct {
	Name        string
	Description string
}

type RolePermission struct {
	Role   string
	Action string
}

type RoutePermission struct {
	Method     string
	Path       string
	Permission *string
	Scope      string
}

type Team struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeamMember struct {
	TeamID    uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Issuer    string
	Subject   string
	Email     *string
	CreatedAt time.Time
	UpdatedAt time.Time
}
