// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"
)

const listRoutePermissions = `-- name: ListRoutePermissions :many
SELECT method, path, permission, scope
FROM route_permissions
ORDER BY path, method
`

func (q *Queries) ListRoutePermissions(ctx context.Context) ([]RoutePermission, error) {
	rows, err := q.db.Query(ctx, listRoutePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoutePermission
	for rows.Next() {
		var i RoutePermission
		if err := rows.Scan(
			&i.Method,
			&i.Path,
			&i.Permission,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
