// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: senders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const approveSender = `-- name: ApproveSender :exec
WITH linked AS (
    INSERT INTO channel_senders (channel_id, sender_ref, user_id)
    VALUES ($1, $2, $3)
    ON CONFLICT (channel_id, sender_ref) DO UPDATE SET user_id = EXCLUDED.user_id
)
DELETE FROM pending_senders
WHERE pending_senders.channel_id = $1
  AND pending_senders.sender_ref = $2
`

type ApproveSenderParams struct {
	ChannelID uuid.UUID
	SenderRef string
	UserID    uuid.UUID
}

// ApproveSender links a sender to a user and takes them out of the queue.
//
// One statement rather than two inside a transaction. Postgres runs a
// statement atomically, and a data-modifying CTE executes to completion
// whether or not the primary query reads its output — so the link and the
// dequeue cannot come apart, and it is one round trip instead of four.
//
// They have to be atomic because nothing here retries. The gateway's writes
// can be merely idempotent, since the provider sends again; an admin approves
// once. A link left with its pending row in place shows the next admin work
// that is already done, and they approve the same person twice.
func (q *Queries) ApproveSender(ctx context.Context, arg ApproveSenderParams) error {
	_, err := q.db.Exec(ctx, approveSender, arg.ChannelID, arg.SenderRef, arg.UserID)
	return err
}

const countPendingSenders = `-- name: CountPendingSenders :one
SELECT count(*) FROM pending_senders WHERE channel_id = $1
`

func (q *Queries) CountPendingSenders(ctx context.Context, channelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSenders, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePendingSender = `-- name: DeletePendingSender :exec
DELETE FROM pending_senders WHERE channel_id = $1 AND sender_ref = $2
`

type DeletePendingSenderParams struct {
	ChannelID uuid.UUID
	SenderRef string
}

func (q *Queries) DeletePendingSender(ctx context.Context, arg DeletePendingSenderParams) error {
	_, err := q.db.Exec(ctx, deletePendingSender, arg.ChannelID, arg.SenderRef)
	return err
}

const findChannelSender = `-- name: FindChannelSender :one
SELECT user_id FROM channel_senders
WHERE channel_id = $1 AND sender_ref = $2
`

type FindChannelSenderParams struct {
	ChannelID uuid.UUID
	SenderRef string
}

func (q *Queries) FindChannelSender(ctx context.Context, arg FindChannelSenderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findChannelSender, arg.ChannelID, arg.SenderRef)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const linkChannelSender = `-- name: LinkChannelSender :exec
INSERT INTO channel_senders (channel_id, sender_ref, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (channel_id, sender_ref) DO UPDATE SET user_id = EXCLUDED.user_id
`

type LinkChannelSenderParams struct {
	ChannelID uuid.UUID
	SenderRef string
	UserID    uuid.UUID
}

func (q *Queries) LinkChannelSender(ctx context.Context, arg LinkChannelSenderParams) error {
	_, err := q.db.Exec(ctx, linkChannelSender, arg.ChannelID, arg.SenderRef, arg.UserID)
	return err
}

const listChannelSenders = `-- name: ListChannelSenders :many
SELECT channel_id, sender_ref, user_id, created_at FROM channel_senders
WHERE channel_id = $1
  AND (NOT $2::bool
   OR (created_at, sender_ref) < ($3::timestamptz, $4::text))
ORDER BY created_at DESC, sender_ref DESC
LIMIT $5
`

type ListChannelSendersParams struct {
	ChannelID      uuid.UUID
	UseCursor      bool
	AfterCreatedAt time.Time
	AfterRef       string
	PageSize       int32
}

func (q *Queries) ListChannelSenders(ctx context.Context, arg ListChannelSendersParams) ([]ChannelSender, error) {
	rows, err := q.db.Query(ctx, listChannelSenders,
		arg.ChannelID,
		arg.UseCursor,
		arg.AfterCreatedAt,
		arg.AfterRef,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelSender
	for rows.Next() {
		var i ChannelSender
		if err := rows.Scan(
			&i.ChannelID,
			&i.SenderRef,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSenders = `-- name: ListPendingSenders :many
SELECT channel_id, sender_ref, sender_name, first_seen, last_seen, seen_count FROM pending_senders
WHERE channel_id = $1
  AND (NOT $2::bool
   OR (first_seen, sender_ref) < ($3::timestamptz, $4::text))
ORDER BY first_seen DESC, sender_ref DESC
LIMIT $5
`

type ListPendingSendersParams struct {
	ChannelID      uuid.UUID
	UseCursor      bool
	AfterFirstSeen time.Time
	AfterRef       string
	PageSize       int32
}

func (q *Queries) ListPendingSenders(ctx context.Context, arg ListPendingSendersParams) ([]PendingSender, error) {
	rows, err := q.db.Query(ctx, listPendingSenders,
		arg.ChannelID,
		arg.UseCursor,
		arg.AfterFirstSeen,
		arg.AfterRef,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingSender
	for rows.Next() {
		var i PendingSender
		if err := rows.Scan(
			&i.ChannelID,
			&i.SenderRef,
			&i.SenderName,
			&i.FirstSeen,
			&i.LastSeen,
			&i.SeenCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPendingSender = `-- name: RecordPendingSender :execrows
INSERT INTO pending_senders (channel_id, sender_ref, sender_name)
SELECT $1::uuid, $2::text, $3::text
WHERE EXISTS (
        SELECT 1 FROM pending_senders
        WHERE channel_id = $1::uuid
          AND sender_ref = $2::text)
   OR (SELECT count(*) FROM pending_senders
        WHERE channel_id = $1::uuid) < $4::bigint
ON CONFLICT (channel_id, sender_ref) DO UPDATE
SET last_seen  = now(),
    seen_count = pending_senders.seen_count + 1,
    -- Somebody who renames themselves should show under the name they are
    -- using now, or an admin approves a row that no longer matches anything
    -- they can see in the provider.
    sender_name = EXCLUDED.sender_name
`

type RecordPendingSenderParams struct {
	ChannelID  uuid.UUID
	SenderRef  string
	SenderName string
	Cap        int64
}

// RecordPendingSender is one statement rather than a count followed by an
// insert, because the count is a decision an unauthenticated caller races.
// An existing sender is always refreshed; only a *new* one is subject to the
// cap, so a busy channel at its limit still shows accurate last_seen values.
// It reports the rows written, so the caller can tell "recorded" from
// "dropped at the cap" without a second query.
func (q *Queries) RecordPendingSender(ctx context.Context, arg RecordPendingSenderParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordPendingSender,
		arg.ChannelID,
		arg.SenderRef,
		arg.SenderName,
		arg.Cap,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeSender = `-- name: RemoveSender :exec
WITH unlinked AS (
    DELETE FROM channel_senders
    WHERE channel_senders.channel_id = $1
      AND channel_senders.sender_ref = $2
)
DELETE FROM pending_senders
WHERE pending_senders.channel_id = $1
  AND pending_senders.sender_ref = $2
`

type RemoveSenderParams struct {
	ChannelID uuid.UUID
	SenderRef string
}

// RemoveSender is both "this person should not speak here any more" and "this
// pending row is spam". One statement covers both, because the caller cannot
// always tell which they are looking at and the wrong guess leaves a row
// behind.
//
// It is not a block. Their next message queues them again, which is what makes
// a mistaken removal recoverable — and a removal of somebody persistent
// ineffective on its own.
func (q *Queries) RemoveSender(ctx context.Context, arg RemoveSenderParams) error {
	_, err := q.db.Exec(ctx, removeSender, arg.ChannelID, arg.SenderRef)
	return err
}

const unlinkChannelSender = `-- name: UnlinkChannelSender :exec
DELETE FROM channel_senders WHERE channel_id = $1 AND sender_ref = $2
`

type UnlinkChannelSenderParams struct {
	ChannelID uuid.UUID
	SenderRef string
}

func (q *Queries) UnlinkChannelSender(ctx context.Context, arg UnlinkChannelSenderParams) error {
	_, err := q.db.Exec(ctx, unlinkChannelSender, arg.ChannelID, arg.SenderRef)
	return err
}
