// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSessionsByChannel = `-- name: CountSessionsByChannel :one
SELECT count(*) FROM sessions WHERE channel_id = $1
`

func (q *Queries) CountSessionsByChannel(ctx context.Context, channelID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsByChannel, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureSession = `-- name: EnsureSession :one
INSERT INTO sessions (team_id, channel_id, provider_ref, kind)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text
)
ON CONFLICT (channel_id, provider_ref) WHERE status = 'open'
DO UPDATE SET last_message_at = now()
RETURNING id, team_id, channel_id, provider_ref, kind, status, started_at, last_message_at
`

type EnsureSessionParams struct {
	TeamID      uuid.UUID
	ChannelID   uuid.UUID
	ProviderRef string
	Kind        string
}

// EnsureSession is find-or-create and "somebody spoke" in one statement.
//
// ON CONFLICT names the partial index's predicate, so Postgres infers that
// index rather than looking for a full one — which is what makes a closed
// session invisible to the conflict and the next message open a fresh row.
// Nothing closes a session today; the shape is here so that when something
// does, this query does not change.
//
// kind is deliberately not updated. A conversation does not become a thread
// because one message arrived differently, and the adapter that said "direct"
// the first time is the one that saw it start.
func (q *Queries) EnsureSession(ctx context.Context, arg EnsureSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, ensureSession,
		arg.TeamID,
		arg.ChannelID,
		arg.ProviderRef,
		arg.Kind,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ChannelID,
		&i.ProviderRef,
		&i.Kind,
		&i.Status,
		&i.StartedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, team_id, channel_id, provider_ref, kind, status, started_at, last_message_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ChannelID,
		&i.ProviderRef,
		&i.Kind,
		&i.Status,
		&i.StartedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const listSessionsByChannel = `-- name: ListSessionsByChannel :many
SELECT id, team_id, channel_id, provider_ref, kind, status, started_at, last_message_at FROM sessions
WHERE channel_id = $1
  AND (NOT $2::bool
   OR (last_message_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY last_message_at DESC, id DESC
LIMIT $5
`

type ListSessionsByChannelParams struct {
	ChannelID          *uuid.UUID
	UseCursor          bool
	AfterLastMessageAt time.Time
	AfterID            uuid.UUID
	PageSize           int32
}

func (q *Queries) ListSessionsByChannel(ctx context.Context, arg ListSessionsByChannelParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByChannel,
		arg.ChannelID,
		arg.UseCursor,
		arg.AfterLastMessageAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ChannelID,
			&i.ProviderRef,
			&i.Kind,
			&i.Status,
			&i.StartedAt,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByTeam = `-- name: ListSessionsByTeam :many
SELECT id, team_id, channel_id, provider_ref, kind, status, started_at, last_message_at FROM sessions
WHERE team_id = $1
  AND (NOT $2::bool
   OR (last_message_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY last_message_at DESC, id DESC
LIMIT $5
`

type ListSessionsByTeamParams struct {
	TeamID             uuid.UUID
	UseCursor          bool
	AfterLastMessageAt time.Time
	AfterID            uuid.UUID
	PageSize           int32
}

// ListSessionsByTeam is what a session started from the dashboard appears in,
// since it has no channel to be listed under.
func (q *Queries) ListSessionsByTeam(ctx context.Context, arg ListSessionsByTeamParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByTeam,
		arg.TeamID,
		arg.UseCursor,
		arg.AfterLastMessageAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ChannelID,
			&i.ProviderRef,
			&i.Kind,
			&i.Status,
			&i.StartedAt,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
