// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const ensureSession = `-- name: EnsureSession :one
INSERT INTO sessions (team_id, channel_id, provider_ref, kind, user_id)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text,
    $5::uuid
)
ON CONFLICT (channel_id, provider_ref) WHERE status = 'open'
DO UPDATE SET last_message_at = now()
RETURNING id, team_id, channel_id, provider_ref, kind, status, started_at, last_message_at, user_id
`

type EnsureSessionParams struct {
	TeamID      uuid.UUID
	ChannelID   uuid.UUID
	ProviderRef string
	Kind        string
	UserID      *uuid.UUID
}

// EnsureSession is find-or-create and "somebody spoke" in one statement.
//
// ON CONFLICT names the partial index's predicate, so Postgres infers that
// index rather than looking for a full one — which is what makes a closed
// session invisible to the conflict and the next message open a fresh row.
// Nothing closes a session today; the shape is here so that when something
// does, this query does not change.
//
// kind is deliberately not updated. A conversation does not become a thread
// because one message arrived differently, and the adapter that said "direct"
// the first time is the one that saw it start.
//
// Nor is user_id. For a direct session it is who the conversation is with,
// and that is decided when it starts; letting a later message move it would
// let a second approved sender take over somebody else's private thread.
func (q *Queries) EnsureSession(ctx context.Context, arg EnsureSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, ensureSession,
		arg.TeamID,
		arg.ChannelID,
		arg.ProviderRef,
		arg.Kind,
		arg.UserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ChannelID,
		&i.ProviderRef,
		&i.Kind,
		&i.Status,
		&i.StartedAt,
		&i.LastMessageAt,
		&i.UserID,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, team_id, channel_id, provider_ref, kind, status, started_at, last_message_at, user_id FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ChannelID,
		&i.ProviderRef,
		&i.Kind,
		&i.Status,
		&i.StartedAt,
		&i.LastMessageAt,
		&i.UserID,
	)
	return i, err
}

const listSessionsByChannel = `-- name: ListSessionsByChannel :many
SELECT id, team_id, channel_id, provider_ref, kind, status, started_at, last_message_at, user_id FROM sessions
WHERE channel_id = $1
  AND (kind <> 'direct'
   OR $2::bool
   OR user_id = $3::uuid)
  AND (NOT $4::bool
   OR (last_message_at, id) < ($5::timestamptz, $6::uuid))
ORDER BY last_message_at DESC, id DESC
LIMIT $7
`

type ListSessionsByChannelParams struct {
	ChannelID          *uuid.UUID
	Moderator          bool
	Viewer             uuid.UUID
	UseCursor          bool
	AfterLastMessageAt time.Time
	AfterID            uuid.UUID
	PageSize           int32
}

// A direct session is one person's conversation, and every member of the team
// could read it until this filter existed. The rule:
//
//	group and thread   the whole team, as before — a shared room is shared
//	direct             the person it is with, plus a moderator
//
// `moderator` is passed in rather than decided here, because who may moderate
// is whether the caller holds channel:write in the team, and that mapping is
// data in rbac.json. A role name in this file would put it back in code.
//
// user_id = viewer is null when user_id is null, and null is not true, so a
// direct session whose participant was deleted falls out of every non-
// moderator's list. Invisible is the safe direction for a private message.
func (q *Queries) ListSessionsByChannel(ctx context.Context, arg ListSessionsByChannelParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByChannel,
		arg.ChannelID,
		arg.Moderator,
		arg.Viewer,
		arg.UseCursor,
		arg.AfterLastMessageAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ChannelID,
			&i.ProviderRef,
			&i.Kind,
			&i.Status,
			&i.StartedAt,
			&i.LastMessageAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByTeam = `-- name: ListSessionsByTeam :many
SELECT id, team_id, channel_id, provider_ref, kind, status, started_at, last_message_at, user_id FROM sessions
WHERE team_id = $1
  AND (kind <> 'direct'
   OR $2::bool
   OR user_id = $3::uuid)
  AND (NOT $4::bool
   OR (last_message_at, id) < ($5::timestamptz, $6::uuid))
ORDER BY last_message_at DESC, id DESC
LIMIT $7
`

type ListSessionsByTeamParams struct {
	TeamID             uuid.UUID
	Moderator          bool
	Viewer             uuid.UUID
	UseCursor          bool
	AfterLastMessageAt time.Time
	AfterID            uuid.UUID
	PageSize           int32
}

// ListSessionsByTeam is what a session started from the dashboard appears in,
// since it has no channel to be listed under. Same visibility rule.
func (q *Queries) ListSessionsByTeam(ctx context.Context, arg ListSessionsByTeamParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByTeam,
		arg.TeamID,
		arg.Moderator,
		arg.Viewer,
		arg.UseCursor,
		arg.AfterLastMessageAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ChannelID,
			&i.ProviderRef,
			&i.Kind,
			&i.Status,
			&i.StartedAt,
			&i.LastMessageAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
