// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (team_id, name, description, body)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, name, description, body, created_at, updated_at
`

type CreateSkillParams struct {
	TeamID      uuid.UUID
	Name        string
	Description string
	Body        string
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.Body,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = $1
`

func (q *Queries) DeleteSkill(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkill, id)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, team_id, name, description, body, created_at, updated_at FROM skills WHERE id = $1
`

func (q *Queries) GetSkill(ctx context.Context, id uuid.UUID) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkillsByTeam = `-- name: ListSkillsByTeam :many
SELECT id, team_id, name, description, created_at, updated_at FROM skills
WHERE team_id = $1
  AND (NOT $2::bool
   OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListSkillsByTeamParams struct {
	TeamID         uuid.UUID
	UseCursor      bool
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageSize       int32
}

type ListSkillsByTeamRow struct {
	ID          uuid.UUID
	TeamID      uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// The body is left out: a page of fifty skills is fifty descriptions to choose
// between, not fifty documents nobody asked to read.
func (q *Queries) ListSkillsByTeam(ctx context.Context, arg ListSkillsByTeamParams) ([]ListSkillsByTeamRow, error) {
	rows, err := q.db.Query(ctx, listSkillsByTeam,
		arg.TeamID,
		arg.UseCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillsByTeamRow
	for rows.Next() {
		var i ListSkillsByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills SET
    name        = $1,
    description = $2,
    body        = $3,
    updated_at  = now()
WHERE id = $4
RETURNING id, team_id, name, description, body, created_at, updated_at
`

type UpdateSkillParams struct {
	Name        string
	Description string
	Body        string
	ID          uuid.UUID
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.Name,
		arg.Description,
		arg.Body,
		arg.ID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
