// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill_files.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clearSkillFiles = `-- name: ClearSkillFiles :exec
DELETE FROM skill_files WHERE skill_id = $1
`

// A replace clears the old directory before writing the new one. The delete
// trigger tombstones every old object, so the bytes of files a new upload
// dropped are swept rather than left behind.
func (q *Queries) ClearSkillFiles(ctx context.Context, skillID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearSkillFiles, skillID)
	return err
}

const getSkillFile = `-- name: GetSkillFile :one
SELECT skill_id, team_id, path, size, sha256, media_type, object_key, created_at FROM skill_files WHERE skill_id = $1 AND path = $2
`

type GetSkillFileParams struct {
	SkillID uuid.UUID
	Path    string
}

func (q *Queries) GetSkillFile(ctx context.Context, arg GetSkillFileParams) (SkillFile, error) {
	row := q.db.QueryRow(ctx, getSkillFile, arg.SkillID, arg.Path)
	var i SkillFile
	err := row.Scan(
		&i.SkillID,
		&i.TeamID,
		&i.Path,
		&i.Size,
		&i.Sha256,
		&i.MediaType,
		&i.ObjectKey,
		&i.CreatedAt,
	)
	return i, err
}

type InsertSkillFilesParams struct {
	SkillID   uuid.UUID
	TeamID    uuid.UUID
	Path      string
	Size      int64
	Sha256    []byte
	MediaType string
	ObjectKey string
}

const listSkillFiles = `-- name: ListSkillFiles :many
SELECT skill_id, team_id, path, size, sha256, media_type, object_key, created_at FROM skill_files WHERE skill_id = $1 ORDER BY path
`

func (q *Queries) ListSkillFiles(ctx context.Context, skillID uuid.UUID) ([]SkillFile, error) {
	rows, err := q.db.Query(ctx, listSkillFiles, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillFile
	for rows.Next() {
		var i SkillFile
		if err := rows.Scan(
			&i.SkillID,
			&i.TeamID,
			&i.Path,
			&i.Size,
			&i.Sha256,
			&i.MediaType,
			&i.ObjectKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
