// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_members.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING team_id, user_id, role, created_at, updated_at
`

type AddTeamMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT u.id, u.subject, u.email, tm.role
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
  AND (NOT $2::bool
       OR (u.subject, u.id) > ($3::text, $4::uuid))
ORDER BY u.subject, u.id
LIMIT $5
`

type ListTeamMembersParams struct {
	TeamID       uuid.UUID
	UseCursor    bool
	AfterSubject string
	AfterID      uuid.UUID
	PageSize     int32
}

type ListTeamMembersRow struct {
	ID      uuid.UUID
	Subject string
	Email   *string
	Role    string
}

func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers,
		arg.TeamID,
		arg.UseCursor,
		arg.AfterSubject,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Email,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT t.id, t.name, tm.role
FROM team_members tm
JOIN teams t ON t.id = tm.team_id
WHERE tm.user_id = $1
ORDER BY t.name
`

type ListUserTeamsRow struct {
	ID   uuid.UUID
	Name string
	Role string
}

func (q *Queries) ListUserTeams(ctx context.Context, userID uuid.UUID) ([]ListUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, listUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTeamsRow
	for rows.Next() {
		var i ListUserTeamsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}
