// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tombstones.sql

package db

import (
	"context"
	"time"
)

const claimDeletedObjects = `-- name: ClaimDeletedObjects :many
UPDATE deleted_objects
SET attempts = attempts + 1, last_attempt_at = now()
WHERE object_key IN (
    SELECT d.object_key FROM deleted_objects d
    WHERE d.last_attempt_at IS NULL OR d.last_attempt_at < $1
    ORDER BY d.last_attempt_at NULLS FIRST, d.deleted_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING object_key, team_id, deleted_at, attempts, last_attempt_at
`

type ClaimDeletedObjectsParams struct {
	RetryBefore *time.Time
	BatchSize   int32
}

// Claim a batch to sweep, and stamp the attempt in the same statement. The
// stamp is the lease: another sweeper ordering by last_attempt_at will not see
// these again until the retry window passes, so two replicas need no election
// between them.
//
// Claiming with an UPDATE rather than SELECT ... FOR UPDATE held open: the
// sweeper makes a network call per object, and a transaction spanning those
// would hold row locks for as long as the object store is slow.
//
// SKIP LOCKED covers the moment two sweepers claim at once. Without it the
// second blocks on the first's rows and then re-reads them, which is the same
// work done twice rather than the next batch done once.
func (q *Queries) ClaimDeletedObjects(ctx context.Context, arg ClaimDeletedObjectsParams) ([]DeletedObject, error) {
	rows, err := q.db.Query(ctx, claimDeletedObjects, arg.RetryBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeletedObject
	for rows.Next() {
		var i DeletedObject
		if err := rows.Scan(
			&i.ObjectKey,
			&i.TeamID,
			&i.DeletedAt,
			&i.Attempts,
			&i.LastAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDeletedSecrets = `-- name: ClaimDeletedSecrets :many
UPDATE deleted_secrets
SET attempts = attempts + 1, last_attempt_at = now()
WHERE path IN (
    SELECT d.path FROM deleted_secrets d
    WHERE d.last_attempt_at IS NULL OR d.last_attempt_at < $1
    ORDER BY d.last_attempt_at NULLS FIRST, d.deleted_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING path, team_id, deleted_at, attempts, last_attempt_at
`

type ClaimDeletedSecretsParams struct {
	RetryBefore *time.Time
	BatchSize   int32
}

// The same three, for the secret store. Kept beside the object ones rather
// than duplicated into a second file: they are one mechanism with two
// destinations, and reading them together is what stops the two drifting.
func (q *Queries) ClaimDeletedSecrets(ctx context.Context, arg ClaimDeletedSecretsParams) ([]DeletedSecret, error) {
	rows, err := q.db.Query(ctx, claimDeletedSecrets, arg.RetryBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeletedSecret
	for rows.Next() {
		var i DeletedSecret
		if err := rows.Scan(
			&i.Path,
			&i.TeamID,
			&i.DeletedAt,
			&i.Attempts,
			&i.LastAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletedObjectBacklog = `-- name: DeletedObjectBacklog :many
SELECT count(*) OVER () AS outstanding, deleted_at AS oldest
FROM deleted_objects
ORDER BY deleted_at
LIMIT 1
`

type DeletedObjectBacklogRow struct {
	Outstanding int64
	Oldest      time.Time
}

// What is still owed. A number that stops falling is a sweeper that stopped,
// and it is the only external sign there is: everything else about an erasure
// looks the same whether the bytes went or not.
//
// One row when anything is outstanding and none when nothing is, which is the
// honest shape: there is no oldest erasure on an empty backlog. min() would
// have to be nullable and sqlc types a nullable aggregate as interface{};
// count(*) OVER () carries the total on the one row this returns instead.
func (q *Queries) DeletedObjectBacklog(ctx context.Context) ([]DeletedObjectBacklogRow, error) {
	rows, err := q.db.Query(ctx, deletedObjectBacklog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeletedObjectBacklogRow
	for rows.Next() {
		var i DeletedObjectBacklogRow
		if err := rows.Scan(&i.Outstanding, &i.Oldest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletedSecretBacklog = `-- name: DeletedSecretBacklog :many
SELECT count(*) OVER () AS outstanding, deleted_at AS oldest
FROM deleted_secrets
ORDER BY deleted_at
LIMIT 1
`

type DeletedSecretBacklogRow struct {
	Outstanding int64
	Oldest      time.Time
}

func (q *Queries) DeletedSecretBacklog(ctx context.Context) ([]DeletedSecretBacklogRow, error) {
	rows, err := q.db.Query(ctx, deletedSecretBacklog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeletedSecretBacklogRow
	for rows.Next() {
		var i DeletedSecretBacklogRow
		if err := rows.Scan(&i.Outstanding, &i.Oldest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forgetDeletedObject = `-- name: ForgetDeletedObject :exec
DELETE FROM deleted_objects WHERE object_key = $1
`

// The object is gone, so the record of work to do goes too. Called only after
// the object store confirms, or after the count above says another row still
// needs those bytes.
func (q *Queries) ForgetDeletedObject(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, forgetDeletedObject, objectKey)
	return err
}

const forgetDeletedSecret = `-- name: ForgetDeletedSecret :exec
DELETE FROM deleted_secrets WHERE path = $1
`

func (q *Queries) ForgetDeletedSecret(ctx context.Context, path string) error {
	_, err := q.db.Exec(ctx, forgetDeletedSecret, path)
	return err
}
