// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findUsersBySubject = `-- name: FindUsersBySubject :many
SELECT id, subject, email
FROM users
WHERE subject = $1::text
ORDER BY id
LIMIT $2
`

type FindUsersBySubjectParams struct {
	Subject  string
	PageSize int32
}

type FindUsersBySubjectRow struct {
	ID      uuid.UUID
	Subject string
	Email   *string
}

func (q *Queries) FindUsersBySubject(ctx context.Context, arg FindUsersBySubjectParams) ([]FindUsersBySubjectRow, error) {
	rows, err := q.db.Query(ctx, findUsersBySubject, arg.Subject, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUsersBySubjectRow
	for rows.Next() {
		var i FindUsersBySubjectRow
		if err := rows.Scan(&i.ID, &i.Subject, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, issuer, subject, email, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, subject, email
FROM users
WHERE (NOT $1::bool OR subject = $2::text)
  AND (NOT $3::bool
       OR (subject, id) > ($4::text, $5::uuid))
ORDER BY subject, id
LIMIT $6
`

type ListUsersParams struct {
	UseSubject   bool
	Subject      string
	UseCursor    bool
	AfterSubject string
	AfterID      uuid.UUID
	PageSize     int32
}

type ListUsersRow struct {
	ID      uuid.UUID
	Subject string
	Email   *string
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.UseSubject,
		arg.Subject,
		arg.UseCursor,
		arg.AfterSubject,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Subject, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (issuer, subject, email)
VALUES ($1, $2, $3)
ON CONFLICT (issuer, subject) DO UPDATE
SET email      = EXCLUDED.email,
    updated_at = now()
RETURNING id, issuer, subject, email, created_at, updated_at
`

type UpsertUserParams struct {
	Issuer  string
	Subject string
	Email   *string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Issuer, arg.Subject, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
