// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const anySuperAdmin = `-- name: AnySuperAdmin :one
SELECT EXISTS (SELECT 1 FROM users WHERE is_super_admin) AS present
`

// Whether anybody holds the grant. Asked before promoting, so it must be the
// whole table rather than one row: the guard is "this install has no admin",
// not "this user is not one".
func (q *Queries) AnySuperAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, anySuperAdmin)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const findUsersBySubject = `-- name: FindUsersBySubject :many
SELECT id, issuer, subject, email
FROM users
WHERE subject = $1::text
ORDER BY id
LIMIT $2
`

type FindUsersBySubjectParams struct {
	Subject  string
	PageSize int32
}

type FindUsersBySubjectRow struct {
	ID      uuid.UUID
	Issuer  string
	Subject string
	Email   *string
}

func (q *Queries) FindUsersBySubject(ctx context.Context, arg FindUsersBySubjectParams) ([]FindUsersBySubjectRow, error) {
	rows, err := q.db.Query(ctx, findUsersBySubject, arg.Subject, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUsersBySubjectRow
	for rows.Next() {
		var i FindUsersBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.Subject,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, issuer, subject, email, created_at, updated_at, is_super_admin FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuperAdmin,
	)
	return i, err
}

const listUserIssuers = `-- name: ListUserIssuers :many
SELECT DISTINCT issuer FROM users ORDER BY issuer
`

func (q *Queries) ListUserIssuers(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserIssuers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var issuer string
		if err := rows.Scan(&issuer); err != nil {
			return nil, err
		}
		items = append(items, issuer)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, issuer, subject, email
FROM users
WHERE (NOT $1::bool OR subject = $2::text)
  AND (NOT $3::bool
       OR (subject, id) > ($4::text, $5::uuid))
ORDER BY subject, id
LIMIT $6
`

type ListUsersParams struct {
	UseSubject   bool
	Subject      string
	UseCursor    bool
	AfterSubject string
	AfterID      uuid.UUID
	PageSize     int32
}

type ListUsersRow struct {
	ID      uuid.UUID
	Issuer  string
	Subject string
	Email   *string
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.UseSubject,
		arg.Subject,
		arg.UseCursor,
		arg.AfterSubject,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.Subject,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFirstUserBootstrap = `-- name: LockFirstUserBootstrap :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Serialises the check-then-promote below. Without it two logins arriving
// together both read "no super admin" and both promote, because they update
// different rows and so never contend for a row lock. Transaction-scoped, so
// it is released by the commit that writes the grant.
func (q *Queries) LockFirstUserBootstrap(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, lockFirstUserBootstrap, key)
	return err
}

const promoteToSuperAdmin = `-- name: PromoteToSuperAdmin :one
UPDATE users SET is_super_admin = true, updated_at = now()
WHERE id = $1
RETURNING id, issuer, subject, email, created_at, updated_at, is_super_admin
`

func (q *Queries) PromoteToSuperAdmin(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, promoteToSuperAdmin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuperAdmin,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (issuer, subject, email)
VALUES ($1, $2, $3)
ON CONFLICT (issuer, subject) DO UPDATE
SET email      = EXCLUDED.email,
    updated_at = now()
RETURNING id, issuer, subject, email, created_at, updated_at, is_super_admin
`

type UpsertUserParams struct {
	Issuer  string
	Subject string
	Email   *string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Issuer, arg.Subject, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuperAdmin,
	)
	return i, err
}
