// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthConfigEnvironment.
const (
	Development AuthConfigEnvironment = "development"
	Production  AuthConfigEnvironment = "production"
	Staging     AuthConfigEnvironment = "staging"
	Test        AuthConfigEnvironment = "test"
)

// Valid indicates whether the value is a known member of the AuthConfigEnvironment enum.
func (e AuthConfigEnvironment) Valid() bool {
	switch e {
	case Development:
		return true
	case Production:
		return true
	case Staging:
		return true
	case Test:
		return true
	default:
		return false
	}
}

// Defines values for WhoamiKind.
const (
	Dev     WhoamiKind = "dev"
	Service WhoamiKind = "service"
	User    WhoamiKind = "user"
)

// Valid indicates whether the value is a known member of the WhoamiKind enum.
func (e WhoamiKind) Valid() bool {
	switch e {
	case Dev:
		return true
	case Service:
		return true
	case User:
		return true
	default:
		return false
	}
}

// AddMemberRequest defines model for AddMemberRequest.
type AddMemberRequest struct {
	// Role Must name a row in `roles`. Ships with `admin` and `developer`;
	// deployments may add their own.
	//
	//
	// Examples: developer
	Role   string             `json:"role"`
	UserID openapi_types.UUID `json:"user_id"`
}

// AuthConfig defines model for AuthConfig.
type AuthConfig struct {
	// DevTokenAccepted True only when a development token is configured *and* the
	// environment is development. The value is never published — a
	// client sends the one it already holds in its own environment.
	DevTokenAccepted bool `json:"dev_token_accepted"`

	// Environment What this deployment considers itself. A client uses it to decide
	// whether a shared token is even worth trying.
	Environment AuthConfigEnvironment `json:"environment"`

	// Oidc Absent when no identity provider is configured, rather than present
	// and blank: a client that branches on the key being there would
	// otherwise build a discovery URL out of an empty issuer.
	Oidc *OIDCConfig `json:"oidc,omitempty"`
}

// AuthConfigEnvironment What this deployment considers itself. A client uses it to decide
// whether a shared token is even worth trying.
type AuthConfigEnvironment string

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	// Name Trimmed before it is stored, and unique across teams. A name of
	// only whitespace is a 400.
	Name string `json:"name"`
}

// Member defines model for Member.
type Member struct {
	// Email Absent when the provider released none
	Email *openapi_types.Email `json:"email,omitempty"`

	// Role Examples: developer
	Role string `json:"role"`

	// Subject The member's identifier at their provider
	Subject string             `json:"subject"`
	UserID  openapi_types.UUID `json:"user_id"`
}

// MemberPage defines model for MemberPage.
type MemberPage struct {
	Items []Member `json:"items"`

	// NextCursor Absent on the last page
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Membership defines model for Membership.
type Membership struct {
	ID   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`

	// Role Examples: admin
	Role string `json:"role"`
}

// OIDCConfig Absent when no identity provider is configured, rather than present
// and blank: a client that branches on the key being there would
// otherwise build a discovery URL out of an empty issuer.
type OIDCConfig struct {
	// ClientID OPENARITY_OIDC_AUDIENCE. The brain checks it as an audience; a
	// client sends it as a client id. Same value, two names, because
	// each side calls it what its own specification calls it.
	ClientID string `json:"client_id"`

	// Issuer Served verbatim, trailing slash included. Discovery lives at
	// `<issuer>/.well-known/openid-configuration`, and the device
	// authorization endpoint is read from there rather than guessed.
	//
	//
	// Examples: http://localhost:9000/application/o/openarity/
	Issuer string `json:"issuer"`
}

// Team defines model for Team.
type Team struct {
	ID openapi_types.UUID `json:"id"`

	// Name Examples: platform
	Name string `json:"name"`

	// Role The caller's role in this team. Absent when they are not a member,
	// which is the normal case for a super admin.
	//
	//
	// Examples: admin
	Role *string `json:"role,omitempty"`
}

// TeamPage defines model for TeamPage.
type TeamPage struct {
	Items []Team `json:"items"`

	// NextCursor Absent on the last page. Its absence is the only end-of-collection
	// signal — there is no separate flag to disagree with it.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Whoami defines model for Whoami.
type Whoami struct {
	// Email Absent when the provider released none
	Email *openapi_types.Email `json:"email,omitempty"`

	// Issuer The identity provider that issued the token
	Issuer *string `json:"issuer,omitempty"`

	// Kind How the caller authenticated
	Kind WhoamiKind `json:"kind"`

	// Subject The caller's stable identifier at that issuer. This is what
	// OPENARITY_SUPER_ADMINS matches on.
	Subject string `json:"subject"`

	// Teams Every team the caller belongs to, never a page
	Teams []Membership `json:"teams"`
}

// WhoamiKind How the caller authenticated
type WhoamiKind string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int32

// TeamID defines model for TeamID.
type TeamID = openapi_types.UUID

// ListTeamsParams defines parameters for ListTeams.
type ListTeamsParams struct {
	// Limit Rows per page. A value above the maximum is clamped rather than
	// refused; zero, a negative and anything unparseable are 400.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor An opaque position, taken verbatim from the `next_cursor` of the
	// previous page. It is not constructible by a client, and one that has
	// been altered is a 400 rather than a silent restart.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListTeamMembersParams defines parameters for ListTeamMembers.
type ListTeamMembersParams struct {
	// Limit Rows per page. A value above the maximum is clamped rather than
	// refused; zero, a negative and anything unparseable are 400.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor An opaque position, taken verbatim from the `next_cursor` of the
	// previous page. It is not constructible by a client, and one that has
	// been altered is a 400 rather than a silent restart.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody = CreateTeamRequest

// AddTeamMemberJSONRequestBody defines body for AddTeamMember for application/json ContentType.
type AddTeamMemberJSONRequestBody = AddMemberRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetAuthConfig How to obtain a token
	//
	// Unauthenticated, because a client holding no credential has to start
	// somewhere. It reports which flow this deployment accepts and the
	// parameters that flow needs, so a client is configured with one address
	// rather than with a copy of the service's own settings.
	//
	// It carries no secret. The issuer and client id are public by OAuth's
	// design for a public client, and the development token is reported as
	// accepted, never as a value.
	//
	// Corresponds with GET /auth/config (the `GetAuthConfig` operationId).
	GetAuthConfig(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth Liveness
	//
	// Answers as long as the process is running. It never touches the
	// database, so a Postgres outage must not restart the pod.
	//
	// Corresponds with GET /healthz (the `GetHealth` operationId).
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReady Readiness
	//
	// Pings Postgres. The body never names the underlying error; the reason
	// is logged instead.
	//
	// Corresponds with GET /readyz (the `GetReady` operationId).
	GetReady(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListTeams List teams
	//
	// A super admin sees every team, paged. Everyone else sees the teams
	// they belong to, with their role in each, in a single page with no
	// cursor — a person's own memberships are bounded.
	//
	// Corresponds with GET /teams (the `ListTeams` operationId).
	ListTeams(ctx context.Context, params *ListTeamsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateTeamWithBody Create a team
	//
	// Super admins only. Creating a team is platform-scoped, so there is no
	// team to check a role against.
	//
	// The new team has no members. A super admin adds the first one, who is
	// then able to manage the rest.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /teams (the `CreateTeam` operationId).
	CreateTeamWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateTeam Create a team
	//
	// Super admins only. Creating a team is platform-scoped, so there is no
	// team to check a role against.
	//
	// The new team has no members. A super admin adds the first one, who is
	// then able to manage the rest.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /teams (the `CreateTeam` operationId).
	CreateTeam(ctx context.Context, body CreateTeamJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTeam Read one team
	//
	// Members and super admins only. A team the caller may not see and a
	// team that does not exist answer identically — a 403 would confirm the
	// id is real.
	//
	// Corresponds with GET /teams/{id} (the `GetTeam` operationId).
	GetTeam(ctx context.Context, id TeamID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListTeamMembers List a team's members
	//
	// A read, so seeing the team is enough — no action is required.
	//
	// Corresponds with GET /teams/{id}/members (the `ListTeamMembers` operationId).
	ListTeamMembers(ctx context.Context, id TeamID, params *ListTeamMembersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddTeamMemberWithBody Add a member
	//
	// Requires `member:write` in this team. The role is checked by the
	// database rather than the service: roles are rows, so an unknown one is
	// a rejected foreign key and comes back as a 400.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /teams/{id}/members (the `AddTeamMember` operationId).
	AddTeamMemberWithBody(ctx context.Context, id TeamID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddTeamMember Add a member
	//
	// Requires `member:write` in this team. The role is checked by the
	// database rather than the service: roles are rows, so an unknown one is
	// a rejected foreign key and comes back as a 400.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /teams/{id}/members (the `AddTeamMember` operationId).
	AddTeamMember(ctx context.Context, id TeamID, body AddTeamMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RemoveTeamMember Remove a member
	//
	// Requires `member:write` in this team. Removing someone who is not a
	// member succeeds: the caller asked for a state, and that state holds.
	//
	// Corresponds with DELETE /teams/{id}/members/{userID} (the `RemoveTeamMember` operationId).
	RemoveTeamMember(ctx context.Context, id TeamID, userID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWhoami The authenticated caller
	//
	// Resolves the token to a user, creating the row on first sight, and
	// returns their team memberships. The user id is deliberately not
	// published — it is a surrogate key, not an address.
	//
	// Corresponds with GET /whoami (the `GetWhoami` operationId).
	GetWhoami(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetAuthConfig How to obtain a token
//
// Unauthenticated, because a client holding no credential has to start
// somewhere. It reports which flow this deployment accepts and the
// parameters that flow needs, so a client is configured with one address
// rather than with a copy of the service's own settings.
//
// It carries no secret. The issuer and client id are public by OAuth's
// design for a public client, and the development token is reported as
// accepted, never as a value.
//
// Corresponds with GET /auth/config (the `GetAuthConfig` operationId).
func (c *Client) GetAuthConfig(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuthConfigRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHealth Liveness
//
// Answers as long as the process is running. It never touches the
// database, so a Postgres outage must not restart the pod.
//
// Corresponds with GET /healthz (the `GetHealth` operationId).
func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetReady Readiness
//
// Pings Postgres. The body never names the underlying error; the reason
// is logged instead.
//
// Corresponds with GET /readyz (the `GetReady` operationId).
func (c *Client) GetReady(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReadyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListTeams List teams
//
// A super admin sees every team, paged. Everyone else sees the teams
// they belong to, with their role in each, in a single page with no
// cursor — a person's own memberships are bounded.
//
// Corresponds with GET /teams (the `ListTeams` operationId).
func (c *Client) ListTeams(ctx context.Context, params *ListTeamsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTeamsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateTeamWithBody Create a team
//
// Super admins only. Creating a team is platform-scoped, so there is no
// team to check a role against.
//
// The new team has no members. A super admin adds the first one, who is
// then able to manage the rest.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /teams (the `CreateTeam` operationId).
func (c *Client) CreateTeamWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTeamRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateTeam Create a team
//
// Super admins only. Creating a team is platform-scoped, so there is no
// team to check a role against.
//
// The new team has no members. A super admin adds the first one, who is
// then able to manage the rest.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /teams (the `CreateTeam` operationId).
func (c *Client) CreateTeam(ctx context.Context, body CreateTeamJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTeamRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetTeam Read one team
//
// Members and super admins only. A team the caller may not see and a
// team that does not exist answer identically — a 403 would confirm the
// id is real.
//
// Corresponds with GET /teams/{id} (the `GetTeam` operationId).
func (c *Client) GetTeam(ctx context.Context, id TeamID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTeamRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListTeamMembers List a team's members
//
// A read, so seeing the team is enough — no action is required.
//
// Corresponds with GET /teams/{id}/members (the `ListTeamMembers` operationId).
func (c *Client) ListTeamMembers(ctx context.Context, id TeamID, params *ListTeamMembersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTeamMembersRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AddTeamMemberWithBody Add a member
//
// Requires `member:write` in this team. The role is checked by the
// database rather than the service: roles are rows, so an unknown one is
// a rejected foreign key and comes back as a 400.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /teams/{id}/members (the `AddTeamMember` operationId).
func (c *Client) AddTeamMemberWithBody(ctx context.Context, id TeamID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddTeamMemberRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AddTeamMember Add a member
//
// Requires `member:write` in this team. The role is checked by the
// database rather than the service: roles are rows, so an unknown one is
// a rejected foreign key and comes back as a 400.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /teams/{id}/members (the `AddTeamMember` operationId).
func (c *Client) AddTeamMember(ctx context.Context, id TeamID, body AddTeamMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddTeamMemberRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RemoveTeamMember Remove a member
//
// Requires `member:write` in this team. Removing someone who is not a
// member succeeds: the caller asked for a state, and that state holds.
//
// Corresponds with DELETE /teams/{id}/members/{userID} (the `RemoveTeamMember` operationId).
func (c *Client) RemoveTeamMember(ctx context.Context, id TeamID, userID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRemoveTeamMemberRequest(c.Server, id, userID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetWhoami The authenticated caller
//
// Resolves the token to a user, creating the row on first sight, and
// returns their team memberships. The user id is deliberately not
// published — it is a surrogate key, not an address.
//
// Corresponds with GET /whoami (the `GetWhoami` operationId).
func (c *Client) GetWhoami(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWhoamiRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAuthConfigRequest constructs an http.Request for the GetAuthConfig method
func NewGetAuthConfigRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/config")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest constructs an http.Request for the GetHealth method
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetReadyRequest constructs an http.Request for the GetReady method
func NewGetReadyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListTeamsRequest constructs an http.Request for the ListTeams method
func NewListTeamsRequest(server string, params *ListTeamsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/teams")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateTeamRequest calls the generic CreateTeam builder with application/json body
func NewCreateTeamRequest(server string, body CreateTeamJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateTeamRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateTeamRequestWithBody constructs an http.Request for the CreateTeam method, with any body, and a specified content type
func NewCreateTeamRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/teams")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTeamRequest constructs an http.Request for the GetTeam method
func NewGetTeamRequest(server string, id TeamID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/teams/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListTeamMembersRequest constructs an http.Request for the ListTeamMembers method
func NewListTeamMembersRequest(server string, id TeamID, params *ListTeamMembersParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/teams/%s/members", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddTeamMemberRequest calls the generic AddTeamMember builder with application/json body
func NewAddTeamMemberRequest(server string, id TeamID, body AddTeamMemberJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddTeamMemberRequestWithBody(server, id, "application/json", bodyReader)
}

// NewAddTeamMemberRequestWithBody constructs an http.Request for the AddTeamMember method, with any body, and a specified content type
func NewAddTeamMemberRequestWithBody(server string, id TeamID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/teams/%s/members", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRemoveTeamMemberRequest constructs an http.Request for the RemoveTeamMember method
func NewRemoveTeamMemberRequest(server string, id TeamID, userID openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "userID", userID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/teams/%s/members/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetWhoamiRequest constructs an http.Request for the GetWhoami method
func NewGetWhoamiRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/whoami")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetAuthConfigWithResponse How to obtain a token
	//
	// Unauthenticated, because a client holding no credential has to start
	// somewhere. It reports which flow this deployment accepts and the
	// parameters that flow needs, so a client is configured with one address
	// rather than with a copy of the service's own settings.
	//
	// It carries no secret. The issuer and client id are public by OAuth's
	// design for a public client, and the development token is reported as
	// accepted, never as a value.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /auth/config (the `GetAuthConfig` operationId).
	GetAuthConfigWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAuthConfigResponse, error)

	// GetHealthWithResponse Liveness
	//
	// Answers as long as the process is running. It never touches the
	// database, so a Postgres outage must not restart the pod.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /healthz (the `GetHealth` operationId).
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// GetReadyWithResponse Readiness
	//
	// Pings Postgres. The body never names the underlying error; the reason
	// is logged instead.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /readyz (the `GetReady` operationId).
	GetReadyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetReadyResponse, error)

	// ListTeamsWithResponse List teams
	//
	// A super admin sees every team, paged. Everyone else sees the teams
	// they belong to, with their role in each, in a single page with no
	// cursor — a person's own memberships are bounded.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /teams (the `ListTeams` operationId).
	ListTeamsWithResponse(ctx context.Context, params *ListTeamsParams, reqEditors ...RequestEditorFn) (*ListTeamsResponse, error)

	// CreateTeamWithBodyWithResponse Create a team
	//
	// Super admins only. Creating a team is platform-scoped, so there is no
	// team to check a role against.
	//
	// The new team has no members. A super admin adds the first one, who is
	// then able to manage the rest.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /teams (the `CreateTeam` operationId).
	CreateTeamWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTeamResponse, error)

	// CreateTeamWithResponse Create a team
	//
	// Super admins only. Creating a team is platform-scoped, so there is no
	// team to check a role against.
	//
	// The new team has no members. A super admin adds the first one, who is
	// then able to manage the rest.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /teams (the `CreateTeam` operationId).
	CreateTeamWithResponse(ctx context.Context, body CreateTeamJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTeamResponse, error)

	// GetTeamWithResponse Read one team
	//
	// Members and super admins only. A team the caller may not see and a
	// team that does not exist answer identically — a 403 would confirm the
	// id is real.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /teams/{id} (the `GetTeam` operationId).
	GetTeamWithResponse(ctx context.Context, id TeamID, reqEditors ...RequestEditorFn) (*GetTeamResponse, error)

	// ListTeamMembersWithResponse List a team's members
	//
	// A read, so seeing the team is enough — no action is required.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /teams/{id}/members (the `ListTeamMembers` operationId).
	ListTeamMembersWithResponse(ctx context.Context, id TeamID, params *ListTeamMembersParams, reqEditors ...RequestEditorFn) (*ListTeamMembersResponse, error)

	// AddTeamMemberWithBodyWithResponse Add a member
	//
	// Requires `member:write` in this team. The role is checked by the
	// database rather than the service: roles are rows, so an unknown one is
	// a rejected foreign key and comes back as a 400.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /teams/{id}/members (the `AddTeamMember` operationId).
	AddTeamMemberWithBodyWithResponse(ctx context.Context, id TeamID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddTeamMemberResponse, error)

	// AddTeamMemberWithResponse Add a member
	//
	// Requires `member:write` in this team. The role is checked by the
	// database rather than the service: roles are rows, so an unknown one is
	// a rejected foreign key and comes back as a 400.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /teams/{id}/members (the `AddTeamMember` operationId).
	AddTeamMemberWithResponse(ctx context.Context, id TeamID, body AddTeamMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*AddTeamMemberResponse, error)

	// RemoveTeamMemberWithResponse Remove a member
	//
	// Requires `member:write` in this team. Removing someone who is not a
	// member succeeds: the caller asked for a state, and that state holds.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /teams/{id}/members/{userID} (the `RemoveTeamMember` operationId).
	RemoveTeamMemberWithResponse(ctx context.Context, id TeamID, userID openapi_types.UUID, reqEditors ...RequestEditorFn) (*RemoveTeamMemberResponse, error)

	// GetWhoamiWithResponse The authenticated caller
	//
	// Resolves the token to a user, creating the row on first sight, and
	// returns their team memberships. The user id is deliberately not
	// published — it is a surrogate key, not an address.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /whoami (the `GetWhoami` operationId).
	GetWhoamiWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWhoamiResponse, error)
}

type GetAuthConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AuthConfig
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetAuthConfigResponse) GetJSON200() *AuthConfig {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetAuthConfigResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetAuthConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAuthConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAuthConfigResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r GetHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetReadyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r GetReadyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetReadyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReadyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetReadyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListTeamsResponse401Headers the declared response headers of an HTTP 401 response for ListTeams
type ListTeamsResponse401Headers struct {
	WWWAuthenticate *string
}

type ListTeamsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *TeamPage
	// Headers401 the parsed response headers for an HTTP 401 response
	Headers401 *ListTeamsResponse401Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListTeamsResponse) GetJSON200() *TeamPage {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r ListTeamsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListTeamsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListTeamsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListTeamsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreateTeamResponse401Headers the declared response headers of an HTTP 401 response for CreateTeam
type CreateTeamResponse401Headers struct {
	WWWAuthenticate *string
}

type CreateTeamResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Team
	// Headers401 the parsed response headers for an HTTP 401 response
	Headers401 *CreateTeamResponse401Headers
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateTeamResponse) GetJSON201() *Team {
	return r.JSON201
}

// GetBody returns the raw response body bytes
func (r CreateTeamResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateTeamResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateTeamResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateTeamResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetTeamResponse401Headers the declared response headers of an HTTP 401 response for GetTeam
type GetTeamResponse401Headers struct {
	WWWAuthenticate *string
}

type GetTeamResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Team
	// Headers401 the parsed response headers for an HTTP 401 response
	Headers401 *GetTeamResponse401Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetTeamResponse) GetJSON200() *Team {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetTeamResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetTeamResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTeamResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTeamResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListTeamMembersResponse401Headers the declared response headers of an HTTP 401 response for ListTeamMembers
type ListTeamMembersResponse401Headers struct {
	WWWAuthenticate *string
}

type ListTeamMembersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *MemberPage
	// Headers401 the parsed response headers for an HTTP 401 response
	Headers401 *ListTeamMembersResponse401Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListTeamMembersResponse) GetJSON200() *MemberPage {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r ListTeamMembersResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListTeamMembersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListTeamMembersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListTeamMembersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// AddTeamMemberResponse401Headers the declared response headers of an HTTP 401 response for AddTeamMember
type AddTeamMemberResponse401Headers struct {
	WWWAuthenticate *string
}

type AddTeamMemberResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// Headers401 the parsed response headers for an HTTP 401 response
	Headers401 *AddTeamMemberResponse401Headers
}

// GetBody returns the raw response body bytes
func (r AddTeamMemberResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AddTeamMemberResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddTeamMemberResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AddTeamMemberResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// RemoveTeamMemberResponse401Headers the declared response headers of an HTTP 401 response for RemoveTeamMember
type RemoveTeamMemberResponse401Headers struct {
	WWWAuthenticate *string
}

type RemoveTeamMemberResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// Headers401 the parsed response headers for an HTTP 401 response
	Headers401 *RemoveTeamMemberResponse401Headers
}

// GetBody returns the raw response body bytes
func (r RemoveTeamMemberResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RemoveTeamMemberResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RemoveTeamMemberResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RemoveTeamMemberResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetWhoamiResponse401Headers the declared response headers of an HTTP 401 response for GetWhoami
type GetWhoamiResponse401Headers struct {
	WWWAuthenticate *string
}

type GetWhoamiResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Whoami
	// Headers401 the parsed response headers for an HTTP 401 response
	Headers401 *GetWhoamiResponse401Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetWhoamiResponse) GetJSON200() *Whoami {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetWhoamiResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetWhoamiResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWhoamiResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetWhoamiResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetAuthConfigWithResponse How to obtain a token
//
// Unauthenticated, because a client holding no credential has to start
// somewhere. It reports which flow this deployment accepts and the
// parameters that flow needs, so a client is configured with one address
// rather than with a copy of the service's own settings.
//
// It carries no secret. The issuer and client id are public by OAuth's
// design for a public client, and the development token is reported as
// accepted, never as a value.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /auth/config (the `GetAuthConfig` operationId).
func (c *ClientWithResponses) GetAuthConfigWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAuthConfigResponse, error) {
	rsp, err := c.GetAuthConfig(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuthConfigResponse(rsp)
}

// GetHealthWithResponse Liveness
//
// Answers as long as the process is running. It never touches the
// database, so a Postgres outage must not restart the pod.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /healthz (the `GetHealth` operationId).
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// GetReadyWithResponse Readiness
//
// Pings Postgres. The body never names the underlying error; the reason
// is logged instead.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /readyz (the `GetReady` operationId).
func (c *ClientWithResponses) GetReadyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetReadyResponse, error) {
	rsp, err := c.GetReady(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReadyResponse(rsp)
}

// ListTeamsWithResponse List teams
//
// A super admin sees every team, paged. Everyone else sees the teams
// they belong to, with their role in each, in a single page with no
// cursor — a person's own memberships are bounded.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /teams (the `ListTeams` operationId).
func (c *ClientWithResponses) ListTeamsWithResponse(ctx context.Context, params *ListTeamsParams, reqEditors ...RequestEditorFn) (*ListTeamsResponse, error) {
	rsp, err := c.ListTeams(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListTeamsResponse(rsp)
}

// CreateTeamWithBodyWithResponse Create a team
//
// Super admins only. Creating a team is platform-scoped, so there is no
// team to check a role against.
//
// The new team has no members. A super admin adds the first one, who is
// then able to manage the rest.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /teams (the `CreateTeam` operationId).
func (c *ClientWithResponses) CreateTeamWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTeamResponse, error) {
	rsp, err := c.CreateTeamWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTeamResponse(rsp)
}

// CreateTeamWithResponse Create a team
//
// Super admins only. Creating a team is platform-scoped, so there is no
// team to check a role against.
//
// The new team has no members. A super admin adds the first one, who is
// then able to manage the rest.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /teams (the `CreateTeam` operationId).
func (c *ClientWithResponses) CreateTeamWithResponse(ctx context.Context, body CreateTeamJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTeamResponse, error) {
	rsp, err := c.CreateTeam(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTeamResponse(rsp)
}

// GetTeamWithResponse Read one team
//
// Members and super admins only. A team the caller may not see and a
// team that does not exist answer identically — a 403 would confirm the
// id is real.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /teams/{id} (the `GetTeam` operationId).
func (c *ClientWithResponses) GetTeamWithResponse(ctx context.Context, id TeamID, reqEditors ...RequestEditorFn) (*GetTeamResponse, error) {
	rsp, err := c.GetTeam(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTeamResponse(rsp)
}

// ListTeamMembersWithResponse List a team's members
//
// A read, so seeing the team is enough — no action is required.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /teams/{id}/members (the `ListTeamMembers` operationId).
func (c *ClientWithResponses) ListTeamMembersWithResponse(ctx context.Context, id TeamID, params *ListTeamMembersParams, reqEditors ...RequestEditorFn) (*ListTeamMembersResponse, error) {
	rsp, err := c.ListTeamMembers(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListTeamMembersResponse(rsp)
}

// AddTeamMemberWithBodyWithResponse Add a member
//
// Requires `member:write` in this team. The role is checked by the
// database rather than the service: roles are rows, so an unknown one is
// a rejected foreign key and comes back as a 400.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /teams/{id}/members (the `AddTeamMember` operationId).
func (c *ClientWithResponses) AddTeamMemberWithBodyWithResponse(ctx context.Context, id TeamID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddTeamMemberResponse, error) {
	rsp, err := c.AddTeamMemberWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddTeamMemberResponse(rsp)
}

// AddTeamMemberWithResponse Add a member
//
// Requires `member:write` in this team. The role is checked by the
// database rather than the service: roles are rows, so an unknown one is
// a rejected foreign key and comes back as a 400.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /teams/{id}/members (the `AddTeamMember` operationId).
func (c *ClientWithResponses) AddTeamMemberWithResponse(ctx context.Context, id TeamID, body AddTeamMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*AddTeamMemberResponse, error) {
	rsp, err := c.AddTeamMember(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddTeamMemberResponse(rsp)
}

// RemoveTeamMemberWithResponse Remove a member
//
// Requires `member:write` in this team. Removing someone who is not a
// member succeeds: the caller asked for a state, and that state holds.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /teams/{id}/members/{userID} (the `RemoveTeamMember` operationId).
func (c *ClientWithResponses) RemoveTeamMemberWithResponse(ctx context.Context, id TeamID, userID openapi_types.UUID, reqEditors ...RequestEditorFn) (*RemoveTeamMemberResponse, error) {
	rsp, err := c.RemoveTeamMember(ctx, id, userID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRemoveTeamMemberResponse(rsp)
}

// GetWhoamiWithResponse The authenticated caller
//
// Resolves the token to a user, creating the row on first sight, and
// returns their team memberships. The user id is deliberately not
// published — it is a surrogate key, not an address.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /whoami (the `GetWhoami` operationId).
func (c *ClientWithResponses) GetWhoamiWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWhoamiResponse, error) {
	rsp, err := c.GetWhoami(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWhoamiResponse(rsp)
}

// ParseGetAuthConfigResponse parses an HTTP response from a GetAuthConfigWithResponse call
func ParseGetAuthConfigResponse(rsp *http.Response) (*GetAuthConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAuthConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AuthConfig
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetReadyResponse parses an HTTP response from a GetReadyWithResponse call
func ParseGetReadyResponse(rsp *http.Response) (*GetReadyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReadyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListTeamsResponse parses an HTTP response from a ListTeamsWithResponse call
func ParseListTeamsResponse(rsp *http.Response) (*ListTeamsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListTeamsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TeamPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	switch {
	case rsp.StatusCode == 401:
		var headers ListTeamsResponse401Headers
		if values := rsp.Header.Values("WWW-Authenticate"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "WWW-Authenticate", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.WWWAuthenticate = &value
		}
		response.Headers401 = &headers
	}

	return response, nil
}

// ParseCreateTeamResponse parses an HTTP response from a CreateTeamWithResponse call
func ParseCreateTeamResponse(rsp *http.Response) (*CreateTeamResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateTeamResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Team
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	switch {
	case rsp.StatusCode == 401:
		var headers CreateTeamResponse401Headers
		if values := rsp.Header.Values("WWW-Authenticate"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "WWW-Authenticate", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.WWWAuthenticate = &value
		}
		response.Headers401 = &headers
	}

	return response, nil
}

// ParseGetTeamResponse parses an HTTP response from a GetTeamWithResponse call
func ParseGetTeamResponse(rsp *http.Response) (*GetTeamResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTeamResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Team
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	switch {
	case rsp.StatusCode == 401:
		var headers GetTeamResponse401Headers
		if values := rsp.Header.Values("WWW-Authenticate"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "WWW-Authenticate", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.WWWAuthenticate = &value
		}
		response.Headers401 = &headers
	}

	return response, nil
}

// ParseListTeamMembersResponse parses an HTTP response from a ListTeamMembersWithResponse call
func ParseListTeamMembersResponse(rsp *http.Response) (*ListTeamMembersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListTeamMembersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MemberPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	switch {
	case rsp.StatusCode == 401:
		var headers ListTeamMembersResponse401Headers
		if values := rsp.Header.Values("WWW-Authenticate"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "WWW-Authenticate", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.WWWAuthenticate = &value
		}
		response.Headers401 = &headers
	}

	return response, nil
}

// ParseAddTeamMemberResponse parses an HTTP response from a AddTeamMemberWithResponse call
func ParseAddTeamMemberResponse(rsp *http.Response) (*AddTeamMemberResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddTeamMemberResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 401:
		var headers AddTeamMemberResponse401Headers
		if values := rsp.Header.Values("WWW-Authenticate"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "WWW-Authenticate", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.WWWAuthenticate = &value
		}
		response.Headers401 = &headers
	}

	return response, nil
}

// ParseRemoveTeamMemberResponse parses an HTTP response from a RemoveTeamMemberWithResponse call
func ParseRemoveTeamMemberResponse(rsp *http.Response) (*RemoveTeamMemberResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RemoveTeamMemberResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 401:
		var headers RemoveTeamMemberResponse401Headers
		if values := rsp.Header.Values("WWW-Authenticate"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "WWW-Authenticate", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.WWWAuthenticate = &value
		}
		response.Headers401 = &headers
	}

	return response, nil
}

// ParseGetWhoamiResponse parses an HTTP response from a GetWhoamiWithResponse call
func ParseGetWhoamiResponse(rsp *http.Response) (*GetWhoamiResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWhoamiResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Whoami
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	switch {
	case rsp.StatusCode == 401:
		var headers GetWhoamiResponse401Headers
		if values := rsp.Header.Values("WWW-Authenticate"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "WWW-Authenticate", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.WWWAuthenticate = &value
		}
		response.Headers401 = &headers
	}

	return response, nil
}
