/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiRouteImport } from './routes/ui'
import { Route as UiIndexRouteImport } from './routes/ui.index'
import { Route as UiApprovalsRouteImport } from './routes/ui.approvals'
import { Route as UiCallbackRouteImport } from './routes/ui.callback'
import { Route as UiChannelsIndexRouteImport } from './routes/ui.channels.index'
import { Route as UiSessionsIndexRouteImport } from './routes/ui.sessions.index'
import { Route as UiTeamsIndexRouteImport } from './routes/ui.teams.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const UiIndexRoute = UiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UiRoute,
} as any)
const UiApprovalsRoute = UiApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => UiRoute,
} as any)
const UiCallbackRoute = UiCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => UiRoute,
} as any)
const UiChannelsIndexRoute = UiChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => UiRoute,
} as any)
const UiSessionsIndexRoute = UiSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => UiRoute,
} as any)
const UiTeamsIndexRoute = UiTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => UiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ui': typeof UiRouteWithChildren
  '/ui/approvals': typeof UiApprovalsRoute
  '/ui/callback': typeof UiCallbackRoute
  '/ui/': typeof UiIndexRoute
  '/ui/channels/': typeof UiChannelsIndexRoute
  '/ui/sessions/': typeof UiSessionsIndexRoute
  '/ui/teams/': typeof UiTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ui/approvals': typeof UiApprovalsRoute
  '/ui/callback': typeof UiCallbackRoute
  '/ui': typeof UiIndexRoute
  '/ui/channels': typeof UiChannelsIndexRoute
  '/ui/sessions': typeof UiSessionsIndexRoute
  '/ui/teams': typeof UiTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ui': typeof UiRouteWithChildren
  '/ui/approvals': typeof UiApprovalsRoute
  '/ui/callback': typeof UiCallbackRoute
  '/ui/': typeof UiIndexRoute
  '/ui/channels/': typeof UiChannelsIndexRoute
  '/ui/sessions/': typeof UiSessionsIndexRoute
  '/ui/teams/': typeof UiTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ui'
    | '/ui/approvals'
    | '/ui/callback'
    | '/ui/'
    | '/ui/channels/'
    | '/ui/sessions/'
    | '/ui/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ui/approvals'
    | '/ui/callback'
    | '/ui'
    | '/ui/channels'
    | '/ui/sessions'
    | '/ui/teams'
  id:
    | '__root__'
    | '/'
    | '/ui'
    | '/ui/approvals'
    | '/ui/callback'
    | '/ui/'
    | '/ui/channels/'
    | '/ui/sessions/'
    | '/ui/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UiRoute: typeof UiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/': {
      id: '/ui/'
      path: '/'
      fullPath: '/ui/'
      preLoaderRoute: typeof UiIndexRouteImport
      parentRoute: typeof UiRoute
    }
    '/ui/approvals': {
      id: '/ui/approvals'
      path: '/approvals'
      fullPath: '/ui/approvals'
      preLoaderRoute: typeof UiApprovalsRouteImport
      parentRoute: typeof UiRoute
    }
    '/ui/callback': {
      id: '/ui/callback'
      path: '/callback'
      fullPath: '/ui/callback'
      preLoaderRoute: typeof UiCallbackRouteImport
      parentRoute: typeof UiRoute
    }
    '/ui/channels/': {
      id: '/ui/channels/'
      path: '/channels'
      fullPath: '/ui/channels/'
      preLoaderRoute: typeof UiChannelsIndexRouteImport
      parentRoute: typeof UiRoute
    }
    '/ui/sessions/': {
      id: '/ui/sessions/'
      path: '/sessions'
      fullPath: '/ui/sessions/'
      preLoaderRoute: typeof UiSessionsIndexRouteImport
      parentRoute: typeof UiRoute
    }
    '/ui/teams/': {
      id: '/ui/teams/'
      path: '/teams'
      fullPath: '/ui/teams/'
      preLoaderRoute: typeof UiTeamsIndexRouteImport
      parentRoute: typeof UiRoute
    }
  }
}

interface UiRouteChildren {
  UiApprovalsRoute: typeof UiApprovalsRoute
  UiCallbackRoute: typeof UiCallbackRoute
  UiIndexRoute: typeof UiIndexRoute
  UiChannelsIndexRoute: typeof UiChannelsIndexRoute
  UiSessionsIndexRoute: typeof UiSessionsIndexRoute
  UiTeamsIndexRoute: typeof UiTeamsIndexRoute
}

const UiRouteChildren: UiRouteChildren = {
  UiApprovalsRoute: UiApprovalsRoute,
  UiCallbackRoute: UiCallbackRoute,
  UiIndexRoute: UiIndexRoute,
  UiChannelsIndexRoute: UiChannelsIndexRoute,
  UiSessionsIndexRoute: UiSessionsIndexRoute,
  UiTeamsIndexRoute: UiTeamsIndexRoute,
}

const UiRouteWithChildren = UiRoute._addFileChildren(UiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UiRoute: UiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
